version: '3.1'
services:
  stats-server:
    build: ./stat-server/service
    image: stat_server_image
    container_name: stat_server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - DB_NAME=stats
      - DB_PORT=5432
      - DB_HOST=stats-db


  stats-db:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - stat-server.url=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - DB_NAME=ewm
      - DB_HOST=db
      - DB_PORT=5432

  ewm-db:
    image: postgres:14-alpine
    container_name: ewmDb
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
